// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot-server/messages.proto

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HighGoalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HighGoal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double distance = 1;</code>
     * @return The distance.
     */
    double getDistance();

    /**
     * <code>double v_angle = 2;</code>
     * @return The vAngle.
     */
    double getVAngle();

    /**
     * <code>double h_angle = 3;</code>
     * @return The hAngle.
     */
    double getHAngle();
  }
  /**
   * Protobuf type {@code HighGoal}
   */
  public  static final class HighGoal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HighGoal)
      HighGoalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HighGoal.newBuilder() to construct.
    private HighGoal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HighGoal() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HighGoal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HighGoal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              distance_ = input.readDouble();
              break;
            }
            case 17: {

              vAngle_ = input.readDouble();
              break;
            }
            case 25: {

              hAngle_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_HighGoal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_HighGoal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Messages.HighGoal.class, Messages.HighGoal.Builder.class);
    }

    public static final int DISTANCE_FIELD_NUMBER = 1;
    private double distance_;
    /**
     * <code>double distance = 1;</code>
     * @return The distance.
     */
    public double getDistance() {
      return distance_;
    }

    public static final int V_ANGLE_FIELD_NUMBER = 2;
    private double vAngle_;
    /**
     * <code>double v_angle = 2;</code>
     * @return The vAngle.
     */
    public double getVAngle() {
      return vAngle_;
    }

    public static final int H_ANGLE_FIELD_NUMBER = 3;
    private double hAngle_;
    /**
     * <code>double h_angle = 3;</code>
     * @return The hAngle.
     */
    public double getHAngle() {
      return hAngle_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (distance_ != 0D) {
        output.writeDouble(1, distance_);
      }
      if (vAngle_ != 0D) {
        output.writeDouble(2, vAngle_);
      }
      if (hAngle_ != 0D) {
        output.writeDouble(3, hAngle_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (distance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, distance_);
      }
      if (vAngle_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, vAngle_);
      }
      if (hAngle_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, hAngle_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Messages.HighGoal)) {
        return super.equals(obj);
      }
      Messages.HighGoal other = (Messages.HighGoal) obj;

      if (java.lang.Double.doubleToLongBits(getDistance())
          != java.lang.Double.doubleToLongBits(
              other.getDistance())) return false;
      if (java.lang.Double.doubleToLongBits(getVAngle())
          != java.lang.Double.doubleToLongBits(
              other.getVAngle())) return false;
      if (java.lang.Double.doubleToLongBits(getHAngle())
          != java.lang.Double.doubleToLongBits(
              other.getHAngle())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDistance()));
      hash = (37 * hash) + V_ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVAngle()));
      hash = (37 * hash) + H_ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHAngle()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Messages.HighGoal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.HighGoal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.HighGoal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.HighGoal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.HighGoal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.HighGoal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.HighGoal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Messages.HighGoal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Messages.HighGoal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Messages.HighGoal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Messages.HighGoal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Messages.HighGoal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Messages.HighGoal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HighGoal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HighGoal)
        Messages.HighGoalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_HighGoal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_HighGoal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Messages.HighGoal.class, Messages.HighGoal.Builder.class);
      }

      // Construct using Messages.HighGoal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        distance_ = 0D;

        vAngle_ = 0D;

        hAngle_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.internal_static_HighGoal_descriptor;
      }

      @java.lang.Override
      public Messages.HighGoal getDefaultInstanceForType() {
        return Messages.HighGoal.getDefaultInstance();
      }

      @java.lang.Override
      public Messages.HighGoal build() {
        Messages.HighGoal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Messages.HighGoal buildPartial() {
        Messages.HighGoal result = new Messages.HighGoal(this);
        result.distance_ = distance_;
        result.vAngle_ = vAngle_;
        result.hAngle_ = hAngle_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.HighGoal) {
          return mergeFrom((Messages.HighGoal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Messages.HighGoal other) {
        if (other == Messages.HighGoal.getDefaultInstance()) return this;
        if (other.getDistance() != 0D) {
          setDistance(other.getDistance());
        }
        if (other.getVAngle() != 0D) {
          setVAngle(other.getVAngle());
        }
        if (other.getHAngle() != 0D) {
          setHAngle(other.getHAngle());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Messages.HighGoal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Messages.HighGoal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double distance_ ;
      /**
       * <code>double distance = 1;</code>
       * @return The distance.
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>double distance = 1;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(double value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double distance = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        
        distance_ = 0D;
        onChanged();
        return this;
      }

      private double vAngle_ ;
      /**
       * <code>double v_angle = 2;</code>
       * @return The vAngle.
       */
      public double getVAngle() {
        return vAngle_;
      }
      /**
       * <code>double v_angle = 2;</code>
       * @param value The vAngle to set.
       * @return This builder for chaining.
       */
      public Builder setVAngle(double value) {
        
        vAngle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double v_angle = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVAngle() {
        
        vAngle_ = 0D;
        onChanged();
        return this;
      }

      private double hAngle_ ;
      /**
       * <code>double h_angle = 3;</code>
       * @return The hAngle.
       */
      public double getHAngle() {
        return hAngle_;
      }
      /**
       * <code>double h_angle = 3;</code>
       * @param value The hAngle to set.
       * @return This builder for chaining.
       */
      public Builder setHAngle(double value) {
        
        hAngle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double h_angle = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHAngle() {
        
        hAngle_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HighGoal)
    }

    // @@protoc_insertion_point(class_scope:HighGoal)
    private static final Messages.HighGoal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Messages.HighGoal();
    }

    public static Messages.HighGoal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HighGoal>
        PARSER = new com.google.protobuf.AbstractParser<HighGoal>() {
      @java.lang.Override
      public HighGoal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HighGoal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HighGoal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HighGoal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Messages.HighGoal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PowerCellsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PowerCells)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double confidences = 1;</code>
     * @return A list containing the confidences.
     */
    java.util.List<java.lang.Double> getConfidencesList();
    /**
     * <code>repeated double confidences = 1;</code>
     * @return The count of confidences.
     */
    int getConfidencesCount();
    /**
     * <code>repeated double confidences = 1;</code>
     * @param index The index of the element to return.
     * @return The confidences at the given index.
     */
    double getConfidences(int index);

    /**
     * <code>repeated double angles = 2;</code>
     * @return A list containing the angles.
     */
    java.util.List<java.lang.Double> getAnglesList();
    /**
     * <code>repeated double angles = 2;</code>
     * @return The count of angles.
     */
    int getAnglesCount();
    /**
     * <code>repeated double angles = 2;</code>
     * @param index The index of the element to return.
     * @return The angles at the given index.
     */
    double getAngles(int index);
  }
  /**
   * Protobuf type {@code PowerCells}
   */
  public  static final class PowerCells extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PowerCells)
      PowerCellsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PowerCells.newBuilder() to construct.
    private PowerCells(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PowerCells() {
      confidences_ = emptyDoubleList();
      angles_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PowerCells();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PowerCells(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                confidences_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              confidences_.addDouble(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                confidences_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                confidences_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                angles_ = newDoubleList();
                mutable_bitField0_ |= 0x00000002;
              }
              angles_.addDouble(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                angles_ = newDoubleList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                angles_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          confidences_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          angles_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_PowerCells_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_PowerCells_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Messages.PowerCells.class, Messages.PowerCells.Builder.class);
    }

    public static final int CONFIDENCES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.DoubleList confidences_;
    /**
     * <code>repeated double confidences = 1;</code>
     * @return A list containing the confidences.
     */
    public java.util.List<java.lang.Double>
        getConfidencesList() {
      return confidences_;
    }
    /**
     * <code>repeated double confidences = 1;</code>
     * @return The count of confidences.
     */
    public int getConfidencesCount() {
      return confidences_.size();
    }
    /**
     * <code>repeated double confidences = 1;</code>
     * @param index The index of the element to return.
     * @return The confidences at the given index.
     */
    public double getConfidences(int index) {
      return confidences_.getDouble(index);
    }
    private int confidencesMemoizedSerializedSize = -1;

    public static final int ANGLES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.DoubleList angles_;
    /**
     * <code>repeated double angles = 2;</code>
     * @return A list containing the angles.
     */
    public java.util.List<java.lang.Double>
        getAnglesList() {
      return angles_;
    }
    /**
     * <code>repeated double angles = 2;</code>
     * @return The count of angles.
     */
    public int getAnglesCount() {
      return angles_.size();
    }
    /**
     * <code>repeated double angles = 2;</code>
     * @param index The index of the element to return.
     * @return The angles at the given index.
     */
    public double getAngles(int index) {
      return angles_.getDouble(index);
    }
    private int anglesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getConfidencesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(confidencesMemoizedSerializedSize);
      }
      for (int i = 0; i < confidences_.size(); i++) {
        output.writeDoubleNoTag(confidences_.getDouble(i));
      }
      if (getAnglesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(anglesMemoizedSerializedSize);
      }
      for (int i = 0; i < angles_.size(); i++) {
        output.writeDoubleNoTag(angles_.getDouble(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getConfidencesList().size();
        size += dataSize;
        if (!getConfidencesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        confidencesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 8 * getAnglesList().size();
        size += dataSize;
        if (!getAnglesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        anglesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Messages.PowerCells)) {
        return super.equals(obj);
      }
      Messages.PowerCells other = (Messages.PowerCells) obj;

      if (!getConfidencesList()
          .equals(other.getConfidencesList())) return false;
      if (!getAnglesList()
          .equals(other.getAnglesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConfidencesCount() > 0) {
        hash = (37 * hash) + CONFIDENCES_FIELD_NUMBER;
        hash = (53 * hash) + getConfidencesList().hashCode();
      }
      if (getAnglesCount() > 0) {
        hash = (37 * hash) + ANGLES_FIELD_NUMBER;
        hash = (53 * hash) + getAnglesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Messages.PowerCells parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.PowerCells parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.PowerCells parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.PowerCells parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.PowerCells parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.PowerCells parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.PowerCells parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Messages.PowerCells parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Messages.PowerCells parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Messages.PowerCells parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Messages.PowerCells parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Messages.PowerCells parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Messages.PowerCells prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PowerCells}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PowerCells)
        Messages.PowerCellsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_PowerCells_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_PowerCells_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Messages.PowerCells.class, Messages.PowerCells.Builder.class);
      }

      // Construct using Messages.PowerCells.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        confidences_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        angles_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.internal_static_PowerCells_descriptor;
      }

      @java.lang.Override
      public Messages.PowerCells getDefaultInstanceForType() {
        return Messages.PowerCells.getDefaultInstance();
      }

      @java.lang.Override
      public Messages.PowerCells build() {
        Messages.PowerCells result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Messages.PowerCells buildPartial() {
        Messages.PowerCells result = new Messages.PowerCells(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          confidences_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.confidences_ = confidences_;
        if (((bitField0_ & 0x00000002) != 0)) {
          angles_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.angles_ = angles_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.PowerCells) {
          return mergeFrom((Messages.PowerCells)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Messages.PowerCells other) {
        if (other == Messages.PowerCells.getDefaultInstance()) return this;
        if (!other.confidences_.isEmpty()) {
          if (confidences_.isEmpty()) {
            confidences_ = other.confidences_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureConfidencesIsMutable();
            confidences_.addAll(other.confidences_);
          }
          onChanged();
        }
        if (!other.angles_.isEmpty()) {
          if (angles_.isEmpty()) {
            angles_ = other.angles_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnglesIsMutable();
            angles_.addAll(other.angles_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Messages.PowerCells parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Messages.PowerCells) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.DoubleList confidences_ = emptyDoubleList();
      private void ensureConfidencesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          confidences_ = mutableCopy(confidences_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @return A list containing the confidences.
       */
      public java.util.List<java.lang.Double>
          getConfidencesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(confidences_) : confidences_;
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @return The count of confidences.
       */
      public int getConfidencesCount() {
        return confidences_.size();
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @param index The index of the element to return.
       * @return The confidences at the given index.
       */
      public double getConfidences(int index) {
        return confidences_.getDouble(index);
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @param index The index to set the value at.
       * @param value The confidences to set.
       * @return This builder for chaining.
       */
      public Builder setConfidences(
          int index, double value) {
        ensureConfidencesIsMutable();
        confidences_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @param value The confidences to add.
       * @return This builder for chaining.
       */
      public Builder addConfidences(double value) {
        ensureConfidencesIsMutable();
        confidences_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @param values The confidences to add.
       * @return This builder for chaining.
       */
      public Builder addAllConfidences(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureConfidencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, confidences_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double confidences = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidences() {
        confidences_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList angles_ = emptyDoubleList();
      private void ensureAnglesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          angles_ = mutableCopy(angles_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @return A list containing the angles.
       */
      public java.util.List<java.lang.Double>
          getAnglesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(angles_) : angles_;
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @return The count of angles.
       */
      public int getAnglesCount() {
        return angles_.size();
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @param index The index of the element to return.
       * @return The angles at the given index.
       */
      public double getAngles(int index) {
        return angles_.getDouble(index);
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @param index The index to set the value at.
       * @param value The angles to set.
       * @return This builder for chaining.
       */
      public Builder setAngles(
          int index, double value) {
        ensureAnglesIsMutable();
        angles_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @param value The angles to add.
       * @return This builder for chaining.
       */
      public Builder addAngles(double value) {
        ensureAnglesIsMutable();
        angles_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @param values The angles to add.
       * @return This builder for chaining.
       */
      public Builder addAllAngles(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureAnglesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, angles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double angles = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAngles() {
        angles_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PowerCells)
    }

    // @@protoc_insertion_point(class_scope:PowerCells)
    private static final Messages.PowerCells DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Messages.PowerCells();
    }

    public static Messages.PowerCells getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PowerCells>
        PARSER = new com.google.protobuf.AbstractParser<PowerCells>() {
      @java.lang.Override
      public PowerCells parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PowerCells(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PowerCells> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PowerCells> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Messages.PowerCells getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HighGoal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HighGoal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PowerCells_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PowerCells_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033robot-server/messages.proto\">\n\010HighGoa" +
      "l\022\020\n\010distance\030\001 \001(\001\022\017\n\007v_angle\030\002 \001(\001\022\017\n\007" +
      "h_angle\030\003 \001(\001\"1\n\nPowerCells\022\023\n\013confidenc" +
      "es\030\001 \003(\001\022\016\n\006angles\030\002 \003(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HighGoal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HighGoal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HighGoal_descriptor,
        new java.lang.String[] { "Distance", "VAngle", "HAngle", });
    internal_static_PowerCells_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PowerCells_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PowerCells_descriptor,
        new java.lang.String[] { "Confidences", "Angles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
