//////////////////////////////////////////////////////////////////
// Hi!                                                          //
//////////////////////////////////////////////////////////////////
//                                                              //
// This is main.java, the entry point for our application.      //
//                                                              //
// Code in here should not be touched, unless you are certain   //
// of what you are doing.                                       //
//                                                              //
// This file is auto-generated by WPILib, and for the most part //
// should remain in the state that WPILib gave it to us in.     //
//                                                              //
// If you are looking for the high-level robot file,            //
// with such wonderful features as WPILib Command-Subsystem     //
// timing orchestration, go check out frc.robot.Robot.          //
//                                                              //
// Or if you are looking for where we initialize our subsystems //
// as well as autonomous commands, take a look at               //
// frc.robot.RobotContainer                                     //
//                                                              //
// Please don't touch this file unless absolutely necessary     //
//                                                              //
//////////////////////////////////////////////////////////////////

/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018-2019 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot;

import edu.wpi.first.wpilibj.RobotBase;

/**
 * Do NOT add any static variables to this class, or any initialization at all.
 * Unless you know what you are doing, do not modify this file except to change
 * the parameter class to the startRobot call.
 */
public final class Main {
  private Main() {
  }

  /**
   * Main initialization function. Do not perform any initialization here.
   *
   * <p>
   * If you change your main robot class, change the parameter type.
   */
  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
  }
}
